name: ikvpack
description: A starting point for Dart libraries or applications.
version: 3.1.0
homepage: https://github.com/maxim-saplin/ikvpack
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.0
  js: ^0.7.1
  path: ^1.9.1
  isolate_pool_2:

dev_dependencies:
  lints: 
  test: ^1.17.3
  ikvpack_100:
    path: 'test_versions/1.0.0'
  ikvpack_200:
    path: 'test_versions/2.0.0'