name: ikvpack
description: A starting point for Dart libraries or applications.
version: 3.0.3
homepage: https://github.com/maxim-saplin/ikvpack
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  archive: ^3.1.2
  js: ^0.6.3
  path: ^1.8.1
  isolate_pool_2:

dev_dependencies:
  lints: 
  test: ^1.17.3
  ikvpack_100:
    path: 'test_versions/1.0.0'
  ikvpack_200:
    path: 'test_versions/2.0.0'