name: ikvpack
description: A starting point for Dart libraries or applications.
version: 3.0.2
homepage: https://github.com/maxim-saplin/ikvpack

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  archive: ^3.1.2
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
  ikvpack_100:
    path: 'test_versions/1.0.0'
  ikvpack_200:
    path: 'test_versions/2.0.0'