name: ikvpack_200
description: A starting point for Dart libraries or applications.
version: 2.0.0
homepage: https://github.com/maxim-saplin/ikvpack

environment:
  sdk: ">=2.19.0-0 <3.0.0"

dependencies:
  archive: ^4.0.0
  js: ^0.7.1

dev_dependencies:
  pedantic: ^1.11.0
  