name: ikvpack_100
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/maxim-saplin/ikvpack

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0